apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yolo-test
  name: yolo-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: yolo-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yolo-test
    spec:
      containers:
      - command:
        - python3
        - "client_local.py"
        - "SLEEP_TIME"
        image: ECR_REPO_TAG
        imagePullPolicy: Always
        name: yolov8
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        pool: karpenter-gpu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 20
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: karpenter-gpu


